package automod_legacy

// This list is in alphabethical order
// Open a pr or bug me on discord if you want a word added
var BuiltinSwearWords = map[string]bool{
	"zebi":        true,
	"sorm":        true,
	"3os":        true,
	"zeby":         true,
	"b1tch":       true,
	"zok":    true,
	"zokomk":     true,
	"omk":       true,
	"3asba":      true,
	"asba":     true,
	"aasba":     true,
	"dirab":      true,
	"drab":       true,
	"drb":        true,
	"drbk":       true,
	"dirabk":    true,
	"3osomk":    true,
	"3oss":        true,
	"nam":         true,
	"hanami":        true,
	"nik":        true,
	"nick":       true,
	"niq":        true,
	"nikomk":    true,
	"nikmk":         true,
	"zabour":      true,
	"zabouromk":        true,
	"zabourmk":     true,
	"zbrmk":    true,
	"zabromk":    true,
	"drbomk":        true,
	"dirabomk":       true,
	"dirbmk": true,
	"drbmk":    true,
}
